schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    LoadBalancedServiceInput:
      type: object
      description: ECS container input properties
      properties:
        appName:
          default: demo-app
          type: string
        tasks:
          items:
            default: []
            properties:
              alb:
                properties:
                  basePath:
                    default: ''
                    description: Unique routing path to be used by ALB's target group
                    maxLength: 20
                    minLength: 0
                    type: string
                  containerName:
                    default: main
                    description: The name of the container (as it appears in a container
                      definition) to associate with the load balancer.
                    type: string
                  healthCheckPath:
                    default: /
                    maxLength: 20
                    minLength: 0
                    type: string
                  listener_rule_priority:
                    default: 1
                    description: The LoadBalancer rule priority. A listener can't
                      have multiple rules with the same priority.
                    maximum: 50000
                    minimum: 1
                    type: number
                  port:
                    default: 443
                    description: ''
                    maximum: 65535
                    minimum: 0
                    type: integer
                  protocol:
                    default: HTTP
                    enum:
                    - HTTP
                    - HTTPS
                    type: string
                type: object
              containers:
                default: []
                items:
                  properties:
                    containerPort:
                      default: 443
                      description: For task definitions that use the awsvpc network
                        mode, you should only specify the containerPort
                      maximum: 65535
                      minimum: 0
                      type: integer
                    environment:
                      default: []
                      description: The environment variables to pass to a container.
                      items:
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                        type: object
                      type: array
                    image:
                      default: public.ecr.aws/nginx/nginx:latest
                      description: The image used to start a container. This string
                        is passed directly to the Docker daemon.
                      type: string
                    name:
                      default: main
                      description: The name of a container. If you're linking multiple
                        containers together in a task definition, the name of one
                        container can be entered in the links of another container
                        to connect the containers. Up to 255 letters (uppercase and
                        lowercase), numbers, underscores, and hyphens are allowed.
                      maxLength: 255
                      minLength: 1
                      type: string
                  type: object
                type: array
              cpu:
                default: '1024'
                description: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu
                enum:
                - '1024'
                - '2048'
                - '4096'
                type: string
              ephemeralStorageSizeInGiB:
                default: 21
                description: The total amount, in GiB, of ephemeral storage to set
                  for the task. The minimum supported value is 21 GiB and the maximum
                  supported value is 200 GiB.
                maximum: 200
                minimum: 21
                type: integer
              executionRolePolicy:
                items:
                  properties:
                    action:
                      items:
                        type: string
                      type: array
                    effect:
                      enum:
                      - Allow
                      - Deny
                      type: string
                    resource:
                      items:
                        type: string
                      type: array
                  type: object
                type: array
              memory:
                default: '2048'
                description: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu
                type: string
              serviceInstanceCount:
                default: 1
                description: The number of instantiations of the specified task definition
                  to place and keep running on your cluster.
                maximum: 12
                minimum: 1
                type: integer
            type: object
          type: array

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        dockerfile:
          title: "Dockerfile"
          type: string
          description: "The location of the Dockerfile to build"
          default: "Dockerfile"
          minLength: 1
          maxLength: 100
        unit_test_command:
          title: "Unit test command"
          type: string
          description: "The command to run to unit test the application code"
          default: "echo 'add your unit test command here'"
          minLength: 1
          maxLength: 200
